travis:
  secure:
    BINSTAR_TOKEN: QNad0z2ywMZyIWmRwsBn5v0O6C5kBbz6YuNUzPNsDq6W1Z0fee29HP+jephUhI0oI3cEiUtS/RRqGwnhkZVOK2PHFNXWuFTr55B1jjU6MXRnrdMCkLEDStIc8YxTGjNfdXGz7g+XcNDaZaSFe61zFZ/GyZAu7lsQp9yN54DC3kZaDz6H50XMZtsWd4CF90n0aLMio0m3Rl+6l2x5PWLO08i5UX31btnqCJMoeTCGA2RMYLOZtfHXN9OaufnJ4e5eIykcQMysRckWwY8AuVZc59qp2/P33AHB8JN4pbyf9Sc4fegHjrbhboUHZLuvmZv8OZpY+89DvFUC3XYq/Oc9sDJQa1UF9HtgvS9IGiIVGzokl3X1h3OySgyJX/Fv3srKYziQCFn836+a+7q7xtdcvNXOVKQ7UUoOBHVC9zZuTqWdI1eX5AdhSu5ZX/Dpy2NERli84HULt8xPY4JK53OFDp9OohLkZts3tyCLtkfto/jljGmm8SpmZkq1vlQ3Oh5+6YFoeitm2pKWYNnexRdC3e9M/qKMycZmvF320doROPSQoERQJCMdDBwnGyNdotTFyPgGKpIOh3v5+QXnzb+71OUMclETW5YXrNoMDpghwc7p33KfC2Q2Hj5THc03qO8HS6PkTMJmer8iqa97J7xxo/RPJ7oM6vMHHmjvMii4Ats=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
